"""
姓名生成模块。

该模块提供了中文和英文姓名生成功能，支持：
- 中文姓名：基于常见姓氏和名字组合生成
- 英文姓名：基于常见英文名字和姓氏组合生成
- 自定义双字名概率
"""

import random
from typing import Optional

from ..base import BaseGenerator


class ChineseName(BaseGenerator):
    """
    中文姓名生成器。
    
    基于常见的中文姓氏和名字组合生成随机中文姓名。
    支持单字名和双字名，可以自定义双字名的出现概率。
    
    Args:
        double_name_probability: 生成双字名的概率，范围 0.0-1.0，默认 0.3（30%）
                                例如：0.5 表示 50% 的概率生成双字名
    
    Attributes:
        SURNAMES: 100+ 个常见中文姓氏（如王、李、张等）
        GIVEN_NAMES_SINGLE: 80+ 个常见单字名（如伟、芳、娜等）
        GIVEN_NAMES_DOUBLE: 70+ 个常见双字名（如志强、文博等）
        
    Example:
        >>> gen = ChineseName()
        >>> name = gen.generate()
        >>> print(name)  # 例如：王伟、李志强
        
        >>> # 设置更高的双字名概率
        >>> gen = ChineseName(double_name_probability=0.7)
        >>> name = gen.generate()  # 70% 的概率生成双字名
    """

    # 常见中文姓氏
    SURNAMES = [
        "王",
        "李",
        "张",
        "刘",
        "陈",
        "杨",
        "赵",
        "黄",
        "周",
        "吴",
        "徐",
        "孙",
        "胡",
        "朱",
        "高",
        "林",
        "何",
        "郭",
        "马",
        "罗",
        "梁",
        "宋",
        "郑",
        "谢",
        "韩",
        "唐",
        "冯",
        "于",
        "董",
        "萧",
        "程",
        "曹",
        "袁",
        "邓",
        "许",
        "傅",
        "沈",
        "曾",
        "彭",
        "吕",
        "苏",
        "卢",
        "蒋",
        "蔡",
        "贾",
        "丁",
        "魏",
        "薛",
        "叶",
        "阎",
        "余",
        "潘",
        "杜",
        "戴",
        "夏",
        "钟",
        "汪",
        "田",
        "任",
        "姜",
        "范",
        "方",
        "石",
        "姚",
        "谭",
        "廖",
        "邹",
        "熊",
        "金",
        "陆",
        "郝",
        "孔",
        "白",
        "崔",
        "康",
        "毛",
        "邱",
        "秦",
        "江",
        "史",
        "顾",
        "侯",
        "邵",
        "孟",
        "龙",
        "万",
        "段",
        "雷",
        "钱",
        "汤",
    ]

    # 常见中文名字（单字）
    GIVEN_NAMES_SINGLE = [
        "伟",
        "芳",
        "娜",
        "秀英",
        "敏",
        "静",
        "丽",
        "强",
        "磊",
        "军",
        "洋",
        "勇",
        "艳",
        "杰",
        "娟",
        "涛",
        "明",
        "超",
        "秀兰",
        "霞",
        "平",
        "刚",
        "桂英",
        "建华",
        "文",
        "华",
        "建国",
        "红",
        "玉",
        "雪",
        "梅",
        "辉",
        "鹏",
        "飞",
        "燕",
        "海",
        "波",
        "云",
        "阳",
        "龙",
        "凤",
        "兰",
        "英",
        "玲",
        "慧",
        "欣",
        "悦",
        "思",
        "雨",
        "晨",
        "宇",
        "浩",
        "博",
        "睿",
        "智",
        "文",
        "武",
        "德",
        "仁",
        "义",
        "礼",
        "信",
        "诚",
        "善",
        "美",
        "真",
        "和",
        "平",
        "安",
        "康",
        "健",
        "福",
        "寿",
        "喜",
        "乐",
        "欢",
        "笑",
        "爱",
        "情",
        "心",
    ]

    # 常见中文名字（双字）
    GIVEN_NAMES_DOUBLE = [
        "志强",
        "志明",
        "志华",
        "志勇",
        "志伟",
        "志军",
        "志刚",
        "志远",
        "文博",
        "文华",
        "文强",
        "文军",
        "文杰",
        "文斌",
        "文超",
        "文浩",
        "建华",
        "建国",
        "建强",
        "建军",
        "建明",
        "建平",
        "建伟",
        "建新",
        "明华",
        "明强",
        "明军",
        "明杰",
        "明辉",
        "明远",
        "明德",
        "明志",
        "海波",
        "海涛",
        "海峰",
        "海明",
        "海强",
        "海军",
        "海华",
        "海东",
        "秀英",
        "秀兰",
        "秀华",
        "秀梅",
        "秀芳",
        "秀云",
        "秀珍",
        "秀琴",
        "桂英",
        "桂兰",
        "桂华",
        "桂芳",
        "桂香",
        "桂珍",
        "桂琴",
        "桂梅",
        "玉梅",
        "玉兰",
        "玉华",
        "玉芳",
        "玉珍",
        "玉琴",
        "玉英",
        "玉霞",
        "雪梅",
        "雪华",
        "雪芳",
        "雪珍",
        "雪琴",
        "雪英",
        "雪霞",
        "雪莲",
    ]

    def __init__(self, double_name_probability: float = 0.3):
        """
        初始化中文姓名生成器。

        Args:
            double_name_probability: 生成双字名的概率，默认 0.3（即 30% 的概率生成双字名）
                                    取值范围应在 0.0 到 1.0 之间
        """
        self.double_name_probability = double_name_probability

    def generate(self) -> str:
        """
        生成一个随机的中文姓名。
        
        根据设定的概率随机选择单字名或双字名，与随机选择的姓氏组合。

        Returns:
            str: 生成的中文姓名，格式为"姓+名"（如"王伟"、"李志强"）
            
        Example:
            >>> gen = ChineseName()
            >>> name = gen.generate()
            >>> print(name)
            王伟
        """
        surname = random.choice(self.SURNAMES)

        # 根据概率决定生成单字名还是双字名
        if random.random() < self.double_name_probability:
            given_name = random.choice(self.GIVEN_NAMES_DOUBLE)
        else:
            given_name = random.choice(self.GIVEN_NAMES_SINGLE)

        return surname + given_name


class EnglishName(BaseGenerator):
    """
    英文姓名生成器。
    
    基于常见的英文名字和姓氏组合生成随机英文姓名。
    
    Attributes:
        FIRST_NAMES: 200+ 个常见英文名字（如 James、Mary、John 等）
        LAST_NAMES: 400+ 个常见英文姓氏（如 Smith、Johnson、Williams 等）
        
    Example:
        >>> gen = EnglishName()
        >>> name = gen.generate()
        >>> print(name)  # 例如：John Smith、Mary Johnson
    """

    # 常见英文名字
    FIRST_NAMES = [
        "James",
        "Mary",
        "John",
        "Patricia",
        "Robert",
        "Jennifer",
        "Michael",
        "Linda",
        "William",
        "Elizabeth",
        "David",
        "Barbara",
        "Richard",
        "Susan",
        "Joseph",
        "Jessica",
        "Thomas",
        "Sarah",
        "Charles",
        "Karen",
        "Christopher",
        "Nancy",
        "Daniel",
        "Lisa",
        "Matthew",
        "Betty",
        "Anthony",
        "Margaret",
        "Mark",
        "Sandra",
        "Donald",
        "Ashley",
        "Steven",
        "Kimberly",
        "Paul",
        "Emily",
        "Andrew",
        "Donna",
        "Joshua",
        "Michelle",
        "Kenneth",
        "Dorothy",
        "Kevin",
        "Carol",
        "Brian",
        "Amanda",
        "George",
        "Melissa",
        "Timothy",
        "Deborah",
        "Ronald",
        "Stephanie",
        "Jason",
        "Rebecca",
        "Edward",
        "Sharon",
        "Jeffrey",
        "Laura",
        "Ryan",
        "Cynthia",
        "Jacob",
        "Kathleen",
        "Gary",
        "Amy",
        "Nicholas",
        "Angela",
        "Eric",
        "Shirley",
        "Jonathan",
        "Anna",
        "Stephen",
        "Brenda",
        "Larry",
        "Pamela",
        "Justin",
        "Emma",
        "Scott",
        "Nicole",
        "Brandon",
        "Helen",
        "Benjamin",
        "Samantha",
        "Samuel",
        "Katherine",
        "Frank",
        "Christine",
        "Gregory",
        "Debra",
        "Raymond",
        "Rachel",
        "Alexander",
        "Carolyn",
        "Patrick",
        "Janet",
        "Jack",
        "Catherine",
        "Dennis",
        "Maria",
        "Jerry",
        "Frances",
        "Tyler",
        "Ann",
        "Aaron",
        "Joyce",
        "Jose",
        "Diane",
        "Henry",
        "Alice",
        "Adam",
        "Julie",
        "Douglas",
        "Heather",
        "Nathan",
        "Teresa",
        "Zachary",
        "Gloria",
        "Kyle",
        "Doris",
        "Noah",
        "Megan",
        "Ethan",
        "Beverly",
        "Jeremy",
        "Marie",
        "Walter",
        "Jacqueline",
        "Christian",
        "Andrea",
        "Keith",
        "Kathryn",
        "Roger",
        "Janice",
        "Terry",
        "Jean",
        "Gerald",
        "Victoria",
        "Harold",
        "Hannah",
        "Sean",
        "Lauren",
        "Austin",
        "Martha",
        "Carl",
        "Judith",
        "Arthur",
        "Cheryl",
        "Lawrence",
        "Mildred",
        "Dylan",
        "Joan",
        "Jesse",
        "Evelyn",
        "Jordan",
        "Judith",
        "Bryan",
        "Grace",
        "Billy",
        "Judy",
        "Joe",
        "Megan",
        "Bruce",
        "Julia",
        "Gabriel",
        "Rose",
        "Logan",
        "Theresa",
        "Alan",
        "Brittany",
        "Juan",
        "Diana",
        "Wayne",
        "Brittany",
        "Roy",
        "Jane",
        "Ralph",
        "Lori",
        "Randy",
        "Marilyn",
        "Eugene",
        "Tammy",
        "Vincent",
        "Megan",
        "Russell",
        "Christina",
        "Louis",
        "Kelly",
        "Philip",
        "Denise",
        "Bobby",
        "Marie",
        "Johnny",
        "Frances",
        "Willie",
        "Amber",
        "Albert",
        "Danielle",
        "Arthur",
        "Beverly",
        "Lawrence",
        "Theresa",
    ]

    # 常见英文姓氏
    LAST_NAMES = [
        "Smith",
        "Johnson",
        "Williams",
        "Brown",
        "Jones",
        "Garcia",
        "Miller",
        "Davis",
        "Rodriguez",
        "Martinez",
        "Hernandez",
        "Lopez",
        "Wilson",
        "Anderson",
        "Thomas",
        "Taylor",
        "Moore",
        "Jackson",
        "Martin",
        "Lee",
        "Thompson",
        "White",
        "Harris",
        "Sanchez",
        "Clark",
        "Ramirez",
        "Lewis",
        "Robinson",
        "Walker",
        "Young",
        "Allen",
        "King",
        "Wright",
        "Scott",
        "Torres",
        "Nguyen",
        "Hill",
        "Flores",
        "Green",
        "Adams",
        "Nelson",
        "Baker",
        "Hall",
        "Rivera",
        "Campbell",
        "Mitchell",
        "Carter",
        "Roberts",
        "Gomez",
        "Phillips",
        "Evans",
        "Turner",
        "Diaz",
        "Parker",
        "Cruz",
        "Edwards",
        "Collins",
        "Reyes",
        "Stewart",
        "Morris",
        "Morales",
        "Murphy",
        "Cook",
        "Rogers",
        "Gutierrez",
        "Ortiz",
        "Morgan",
        "Cooper",
        "Peterson",
        "Bailey",
        "Reed",
        "Kelly",
        "Howard",
        "Ramos",
        "Kim",
        "Cox",
        "Ward",
        "Richardson",
        "Watson",
        "Brooks",
        "Chavez",
        "Wood",
        "James",
        "Bennett",
        "Gray",
        "Mendoza",
        "Ruiz",
        "Hughes",
        "Price",
        "Alvarez",
        "Castillo",
        "Sanders",
        "Patel",
        "Myers",
        "Long",
        "Ross",
        "Foster",
        "Jimenez",
        "Powell",
        "Jenkins",
        "Perry",
        "Russell",
        "Sullivan",
        "Bell",
        "Alexander",
        "Martinez",
        "Griffin",
        "Diaz",
        "Hayes",
        "Myers",
        "Ford",
        "Hamilton",
        "Graham",
        "Sullivan",
        "Wallace",
        "Woods",
        "Cole",
        "West",
        "Jordan",
        "Owens",
        "Reynolds",
        "Fisher",
        "Ellis",
        "Harrison",
        "Gibson",
        "Mcdonald",
        "Cruz",
        "Marshall",
        "Ortiz",
        "Gomez",
        "Murray",
        "Freeman",
        "Wells",
        "Webb",
        "Simpson",
        "Stevens",
        "Tucker",
        "Porter",
        "Hunter",
        "Hicks",
        "Crawford",
        "Henry",
        "Boyd",
        "Mason",
        "Morales",
        "Kennedy",
        "Warren",
        "Dixon",
        "Ramos",
        "Reyes",
        "Burns",
        "Gordon",
        "Shaw",
        "Holmes",
        "Rice",
        "Robertson",
        "Hunt",
        "Black",
        "Daniels",
        "Palmer",
        "Mills",
        "Nichols",
        "Grant",
        "Knight",
        "Ferguson",
        "Rose",
        "Stone",
        "Hawkins",
        "Dunn",
        "Perkins",
        "Hudson",
        "Spencer",
        "Gardner",
        "Stephens",
        "Payne",
        "Pierce",
        "Berry",
        "Matthews",
        "Arnold",
        "Wagner",
        "Willis",
        "Ray",
        "Watkins",
        "Olson",
        "Carroll",
        "Duncan",
        "Snyder",
        "Hart",
        "Cunningham",
        "Bradley",
        "Lane",
        "Andrews",
        "Ruiz",
        "Harper",
        "Fox",
        "Riley",
        "Armstrong",
        "Carpenter",
        "Weaver",
        "Greene",
        "Lawrence",
        "Elliott",
        "Chavez",
        "Sims",
        "Austin",
        "Peters",
        "Kelley",
        "Franklin",
        "Lawson",
        "Fields",
        "Gutierrez",
        "Ryan",
        "Schmidt",
        "Carr",
        "Vasquez",
        "Castillo",
        "Wheeler",
        "Chapman",
        "Oliver",
        "Montgomery",
        "Richards",
        "Williamson",
        "Johnston",
        "Banks",
        "Meyer",
        "Bishop",
        "Mccoy",
        "Howell",
        "Alvarez",
        "Morrison",
        "Hansen",
        "Fernandez",
        "Garza",
        "Harvey",
        "Little",
        "Burton",
        "Stanley",
        "Nguyen",
        "George",
        "Jacobs",
        "Reid",
        "Kim",
        "Fuller",
        "Lynch",
        "Dean",
        "Gilbert",
        "Garrett",
        "Romero",
        "Welch",
        "Larson",
        "Frazier",
        "Burke",
        "Hanson",
        "Day",
        "Mendoza",
        "Moreno",
        "Bowman",
        "Medina",
        "Fowler",
        "Brewer",
        "Hoffman",
        "Carlson",
        "Silva",
        "Pearson",
        "Holland",
        "Douglas",
        "Fleming",
        "Jensen",
        "Vargas",
        "Byrd",
        "Davidson",
        "Hopkins",
        "May",
        "Terry",
        "Herrera",
        "Wade",
        "Soto",
        "Walters",
        "Curtis",
        "Neal",
        "Caldwell",
        "Lowe",
        "Jennings",
        "Barnett",
        "Graves",
        "Jimenez",
        "Horton",
        "Shelton",
        "Barrett",
        "Obrien",
        "Castro",
        "Sutton",
        "Gregory",
        "Mckinney",
        "Lucas",
        "Miles",
        "Craig",
        "Rodriquez",
        "Chambers",
        "Holt",
        "Lambert",
        "Fletcher",
        "Watts",
        "Bates",
        "Hale",
        "Rhodes",
        "Pena",
        "Beck",
        "Newman",
        "Haynes",
        "Mcdaniel",
        "Mendez",
        "Bush",
        "Vaughn",
        "Parks",
        "Dawson",
        "Santiago",
        "Norris",
        "Hardy",
        "Love",
        "Steele",
        "Curry",
        "Powers",
        "Schultz",
        "Barker",
        "Guzman",
        "Page",
        "Munoz",
        "Ball",
        "Keller",
        "Chandler",
        "Weber",
        "Leonard",
        "Mann",
        "Lynch",
        "Briggs",
        "Brock",
        "Sharp",
        "Bowen",
        "Daniels",
        "Barber",
        "Cummings",
        "Hines",
        "Baldwin",
        "Griffith",
        "Valdez",
        "Hubbard",
        "Salazar",
        "Reeves",
        "Warner",
        "Stevenson",
        "Burgess",
        "Santos",
        "Tate",
        "Cross",
        "Garner",
        "Mann",
        "Mack",
        "Moss",
        "Thornton",
        "Dennis",
        "Mcgee",
        "Farmer",
        "Delgado",
        "Aguilar",
        "Vega",
        "Glover",
        "Manning",
        "Cohen",
        "Harmon",
        "Rodgers",
        "Robbins",
        "Newton",
        "Todd",
        "Blair",
        "Higgins",
        "Ingram",
        "Reese",
        "Cannon",
        "Strickland",
        "Townsend",
        "Potter",
        "Goodwin",
        "Walton",
        "Rowe",
        "Hampton",
        "Ortega",
        "Patton",
        "Swanson",
        "Joseph",
        "Francis",
        "Goodman",
        "Maldonado",
        "Yates",
        "Becker",
        "Erickson",
        "Hodges",
        "Rios",
        "Conner",
        "Adkins",
        "Webster",
        "Norman",
        "Malone",
        "Hammond",
        "Flowers",
        "Cobb",
        "Moody",
        "Quinn",
        "Blake",
        "Maxwell",
        "Pope",
        "Floyd",
        "Osborne",
        "Paul",
        "Mccarthy",
        "Guerrero",
        "Lindsey",
        "Estrada",
        "Sandoval",
        "Gibbs",
        "Tyler",
        "Gross",
        "Fitzgerald",
        "Stokes",
        "Doyle",
        "Sherman",
        "Saunders",
        "Wise",
        "Colon",
        "Gill",
        "Alvarado",
        "Greer",
        "Padilla",
        "Simon",
        "Waters",
        "Nunez",
        "Ballard",
        "Schwartz",
        "Mcbride",
        "Houston",
        "Christensen",
        "Klein",
        "Pratt",
        "Briggs",
        "Parsons",
        "Mclaughlin",
        "Zimmerman",
        "French",
        "Buchanan",
        "Moran",
        "Copeland",
        "Roy",
        "Pittman",
        "Brady",
        "Mccormick",
        "Holloway",
        "Brock",
        "Poole",
        "Frank",
        "Logan",
        "Owen",
        "Bass",
        "Marsh",
        "Drake",
        "Wong",
        "Jefferson",
        "Park",
        "Morton",
        "Abbott",
        "Sparks",
        "Patrick",
        "Norton",
        "Huff",
        "Clayton",
        "Massey",
        "Lloyd",
        "Figueroa",
        "Carson",
        "Bowers",
        "Roberson",
        "Barton",
        "Tran",
        "Lamb",
        "Harrington",
        "Casey",
        "Boone",
        "Cortez",
        "Clarke",
        "Mathis",
        "Singleton",
        "Wilkins",
        "Cain",
        "Bryan",
        "Underwood",
        "Hogan",
        "Mckenzie",
        "Collier",
        "Juarez",
        "Pruitt",
        "Hughes",
        "Bauer",
        "Gill",
        "Horton",
        "Richards",
        "Holland",
        "Briggs",
        "Valdez",
        "Brewer",
        "Mccarthy",
        "Mcdaniel",
        "Mendez",
        "Bush",
    ]

    def generate(self) -> str:
        """
        生成一个随机的英文姓名。
        
        按照英文姓名习惯，格式为"名字 + 姓氏"（First Name + Last Name）。

        Returns:
            str: 生成的英文姓名，格式为"名字 姓氏"（如 "John Smith"）
            
        Example:
            >>> gen = EnglishName()
            >>> name = gen.generate()
            >>> print(name)
            John Smith
        """
        first_name = random.choice(self.FIRST_NAMES)
        last_name = random.choice(self.LAST_NAMES)
        return f"{first_name} {last_name}"


# 全局单例，用于快速生成姓名
__chinese_name = ChineseName()
__english_name = EnglishName()


def fake_name(language: Optional[str] = None) -> str:
    """
    快速生成随机姓名。
    
    这是一个便捷函数，可以快速生成中文或英文姓名。

    Args:
        language: 语言类型，可选值：
                 - 'chinese': 生成中文姓名
                 - 'english': 生成英文姓名
                 - None: 随机选择中文或英文（默认）

    Returns:
        str: 生成的姓名（中文或英文）
        
    Example:
        >>> from funfake import fake_name
        >>> 
        >>> # 生成中文姓名
        >>> name = fake_name('chinese')
        >>> print(name)  # 王伟
        >>> 
        >>> # 生成英文姓名
        >>> name = fake_name('english')
        >>> print(name)  # John Smith
        >>> 
        >>> # 随机生成
        >>> name = fake_name()  # 可能是中文或英文
    """
    if language == "chinese":
        return __chinese_name.generate()
    elif language == "english":
        return __english_name.generate()
    else:
        # 随机选择中文或英文
        return random.choice([__chinese_name, __english_name]).generate()
